name: "Test calling report.yml"

on:
  workflow_dispatch:
    inputs:
      which-gap:
        description: 'Either a GAP branch name or a GAP version'
        required: true
        type: string
        default: master # or 4.11.1 or ...
      pkg-build-glob:
        description: 'Only build packages matching the given glob'
        required: false
        type: string
        default: "*"
      pkg-test-glob:
        description: 'Only test packages matching the given glob'
        required: false
        type: string
        default: "*"
  workflow_call:
    inputs:
      which-gap:
        description: 'Either a GAP branch name or a GAP version'
        required: true
        type: string
        default: master # or 4.11.1 or ...
      pkg-build-glob:
        description: 'Only build packages matching the given glob'
        required: false
        type: string
        default: "*"
      pkg-test-glob:
        description: 'Only test packages matching the given glob'
        required: false
        type: string
        default: "*"

jobs:
  call-report:
    name: "Call report.yml"
    uses: ./.github/workflows/report.yml
    with:
      which-gap: ${{ github.event.inputs.which-gap || inputs.which-gap }}
      pkg-build-glob: ${{ github.event.inputs.pkg-build-glob || inputs.pkg-build-glob }}
      pkg-test-glob: ${{ github.event.inputs.pkg-test-glob || inputs.pkg-test-glob }}

  update-latest:
    name: "Upload report"
    runs-on: ubuntu-latest
    needs: call-report
    steps:
      - uses: actions/checkout@v2

      - name: "Install package distribution tools"
        run: python -m pip install -r tools/requirements.txt

      - name: "Download report"
        uses: actions/download-artifact@v3
        with:
          name: report-${{ github.event.inputs.which-gap || inputs.which-gap }}
          path: _report

      - name: "Create data and gh-pages worktree"
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git fetch
          git branch --track data origin/data
          git worktree add data data
          git branch --track gh-pages origin/gh-pages
          git worktree add gh-pages gh-pages

      - name: "Update latest report"
        run: |
          ROOT="data/reports"
          DIR_REL=$(jq -r '.id' < '_report/test-status.json')
          DIR="${ROOT}/${DIR_REL}"
          mkdir -p ${DIR}
          mv _report/* ${DIR}
          python tools/update_latest_report.py ${DIR_REL} latest-${{ github.event.inputs.which-gap || inputs.which-gap }}

      - name: "Push report"
        id: push-report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          cd data
          git add -A
          git commit -m "Automated report"
          git push
          cd ../gh-pages
          git add -A
          git commit -m "Automated redirect"
          git push
