name: "Test generation of comparison reports"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Run Tests"
    uses: ./.github/workflows/report-caller.yml


  report:
    name: "Create Report"
    runs-on: ubuntu-latest
    needs: test
    env:
      test-status: ${{ fromJson(needs.test.outputs.test-status) }}
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package distribution tools"
        run: |
          python -m pip install -r tools/requirements.txt

      - name: "Create data and gh-pages worktree"
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git fetch
          git branch --track data origin/data
          git worktree add data data
          git branch --track gh-pages origin/gh-pages
          git worktree add gh-pages gh-pages

      - name: "Generate report"
        id: report
        run: |
          # Generate id for test-status
          ROOT="data/reports"
          JSON='${{ env.test-status }}'
          HASH=$(jq -r '.hash_short' <<< ${JSON})
          DATE=$(jq -r '.date' <<< ${JSON})
          DATE=$(echo $DATE | sed 's/ /-/g' | cut -d '.' -f1)
          DIR_REL="manual/${DATE}-${HASH}"
          DIR="${ROOT}/${DIR_REL}"
          JSON=$(echo ${JSON} | jq '.id |= ["${DIR_REL}"] + .')
          # Write test-status
          mkdir -p ${DIR}
          jq <<< ${JSON} > "${DIR}/test-status.json"
          # Generate report
          python tools/generate_report.py ${DIR_REL}

      - name: "Push report"
        id: push-report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          cd data
          git add -A
          git commit -m "Automated report"
          git push
          cd ../gh-pages
          git add -A
          git commit -m "Automated redirect"
          git push
