name: "Helper for testing report.yml"

on:
  workflow_call:
    outputs:
      test-status:
        description: "The test-status report"
        value: ${{ jobs.report.outputs.test-status }}

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest
    outputs:
      test-status: ${{ steps.test-status.outputs.test-status }}
    steps:
      - uses: actions/checkout@v2

      - name: "Generate test-status.json"
        id: report
        run: python tools/generate_test_status.py ${{ github.repository }} "$GITHUB_RUN_ID" "$GITHUB_SHA" $(git rev-parse --short "$GITHUB_SHA")

      - name: "Output test-status"
        id: test-status
        run: |
          TEST_STATUS=$(cat test-status.json | jq -aRs)
          echo "::set-output name=test-status::$TEST_STATUS"
