name: "Test generation of comparison reports"

on:
  workflow_dispatch:
  push:

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package distribution tools"
        run: |
          python -m pip install -r tools/requirements.txt

      - name: "Generate test-status.json"
        id: test-status
        run: python tools/generate_test_status.py ${{ github.repository }} "$GITHUB_RUN_ID" "$GITHUB_SHA" $(git rev-parse --short "$GITHUB_SHA")

      - name: "Create data and gh-pages worktree"
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git fetch
          git branch --track data origin/data
          git worktree add data data
          git branch --track gh-pages origin/gh-pages
          git worktree add gh-pages gh-pages

      - name: "Generate report"
        id: report
        run: |
          # Generate id for test-status
          ROOT="data/reports"
          JSON=$(cat test-status.json)
          HASH=$(jq -r '.hash_short' <<< ${JSON})
          DATE=$(jq -r '.date' <<< ${JSON})
          DATE=$(echo $DATE | sed 's/ /-/g' | cut -d '.' -f1)
          DIR_REL="manual/${DATE}-${HASH}"
          DIR="${ROOT}/${DIR_REL}"
          JSON=$(echo ${JSON} | jq --arg id $DIR_REL '.id |= $id + .')
          # Write test-status
          mkdir -p ${DIR}
          jq <<< ${JSON} > "${DIR}/test-status.json"
          # Generate report
          python tools/generate_report.py ${DIR_REL} latest

      # - name: "Update latest report"
      #   run: |
      #     python tools/update_latest_report.py ${DIR_REL} latest

      - name: "Push report"
        id: push-report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          cd data
          git add -A
          git commit -m "Automated report"
          git push
          # # CAUTION: Use this only if generate report overwrites latest!
          # cd ../gh-pages
          # git add -A
          # git commit -m "Automated redirect"
          # git push
