name: "Test generation of comparison reports"

on:
  workflow_call:
    inputs:
      which-gap:
        description: 'Which Gap version'
        default: 'master'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      which-gap:
        description: 'Which Gap version'
        default: 'master'
        required: false
        type: string

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package distribution tools"
        run: |
          python -m pip install -r tools/requirements.txt

      - name: "Generate test-status.json"
        id: test-status
        run: python tools/generate_test_status.py ${{ github.repository }} "$GITHUB_RUN_ID" "$GITHUB_SHA" $(git rev-parse --short "$GITHUB_SHA")

      - name: "Create data and gh-pages worktree"
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git fetch
          git branch --track data origin/data
          git worktree add data data
          git branch --track gh-pages origin/gh-pages
          git worktree add gh-pages gh-pages

      - name: "Generate report"
        id: report
        run: |
          # Generate id for test-status
          ROOT="data/reports"
          JSON=$(cat test-status.json)
          HASH=$(jq -r '.hash_short' <<< ${JSON})
          DATE=$(jq -r '.date' <<< ${JSON})
          DATE=$(echo $DATE | sed 's/ /-/g' | cut -d '.' -f1)
          DIR_REL="manual/${DATE}-${HASH}"
          DIR="${ROOT}/${DIR_REL}"
          JSON=$(echo ${JSON} | jq --arg id $DIR_REL '.id |= $id + .')
          # Write test-status
          echo "::set-output name=dir::${DIR}"
          mkdir -p ${DIR}
          jq <<< ${JSON} > "${DIR}/test-status.json"
          # Generate report
          python tools/generate_report.py ${DIR_REL} latest-${{ github.event.inputs.which-gap }}

      - name: "Upload report as artifact"
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: "report-${{ github.event.inputs.which-gap }}"
          path: "${{ steps.report.outputs.dir }}"
