name: "Test generation of comparison reports"

on:
  workflow_call:
    inputs:
      which-gap:
        description: 'Which GAP version'
        default: 'master'
        required: false
        type: string

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - name: "Install package distribution tools"
        run: python -m pip install -r tools/requirements.txt

      - name: "Generate test-status.json"
        id: test-status
        run: |
          ROOT='data/reports'
          # relative path (with respect to ROOT) to generated test-status.json, i.e. the "id" entry of the json-file.
          DIR_REL=$(python tools/generate_test_status.py ${{ github.repository }} "$GITHUB_RUN_ID" "$GITHUB_SHA" ${{ github.event.inputs.which-gap }})
          DIR="${ROOT}/${DIR_REL}"
          echo "::set-output name=dir::${DIR}"
          echo "::set-output name=dir-rel::${DIR_REL}"

      - name: "Download latest report"
        id: download-latest-report
        run: |
          ROOT="data/reports"
          DIR_SYM_REL=latest-${{ github.event.inputs.which-gap }}
          DIR_SYM="${ROOT}/${DIR_SYM_REL}"
          URL_SYM="https://raw.githubusercontent.com/${{ github.repository }}/${DIR_SYM}"
          # Check if file at url exists,
          # so we do not run into errors for the first run of the script
          # (when the first report is created and thus no latest report is available)
          if wget --spider "${URL_SYM}"; then
            # wget downloads the "symbolic link" as a plain file
            # containing as content the path that the symlink points to,
            # so we need to convert this into a real symbolic link.
            DIR_REL=$(wget -O - ${URL_SYM})
            DIR="${ROOT}/${DIR_REL}"
            ln -s ${DIR_REL} ${DIR_SYM}
            URL="https://raw.githubusercontent.com/${{ github.repository }}/${DIR}/test-status.json"
            wget -P ${DIR} ${URL}
          fi

      - name: "Generate report"
        id: report
        run: python tools/generate_report.py ${{ steps.test-status.outputs.dir-rel }} latest-${{ github.event.inputs.which-gap }}

      - name: "Upload report as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "report-${{ github.event.inputs.which-gap }}"
          path: "${{ steps.test-status.outputs.dir }}"
