name: "Test generation of comparison reports"

on:
  workflow_call:
    inputs:
      which-gap:
        description: 'Which Gap version'
        default: 'master'
        required: false
        type: string

jobs:
  report:
    name: "Report"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: "Install package distribution tools"
        run: |
          python -m pip install -r tools/requirements.txt

      - name: "Generate test-status.json"
        id: test-status
        run: |
          ROOT='data/reports'
          DIR_REL=$(python tools/generate_test_status.py ${{ github.repository }} "$GITHUB_RUN_ID" "$GITHUB_SHA" ${{github.event.inputs.which-gap}})
          DIR="${ROOT}/${DIR_REL}"
          echo "::set-output name=dir::${DIR}"
          echo "::set-output name=dir-rel::${DIR_REL}"

      - name: "Download latest report"
        id: download-latest-report
        run: |
          ROOT="data/reports"
          DIR_SYM_REL=latest-${{ github.event.inputs.which-gap }}
          DIR_SYM="${ROOT}/${DIR_SYM_REL}"
          URL_SYM="https://raw.githubusercontent.com/${{ github.repository }}/${DIR_SYM}"
          if curl --head --fail --silent "${URL_SYM}" 2>/dev/null; then
            # wget downloads the symbolic link as file!
            wget -O ${DIR_SYM} ${URL_SYM}
            DIR=$(cat ${DIR_SYM})
            rm ${DIR_SYM}
            ln -s ${DIR} ${DIR_SYM}
            DIR=${DIR#/home/runner/work/PackageDistro/PackageDistro/}
            URL="https://raw.githubusercontent.com/${{ github.repository }}/${DIR}/test-status.json"
            wget -P ${DIR} ${URL}
          fi

      - name: "Generate report"
        id: report
        run: |
          python tools/generate_report.py ${{ steps.test-status.outputs.dir-rel }} latest-${{ github.event.inputs.which-gap }}

      - name: "Upload report as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: "report-${{ github.event.inputs.which-gap }}"
          path: "${{ steps.test-status.outputs.dir }}"
