#
# This workflow is run either by a manual workflow dispatch, or
# as part of a pull request check.
#
# It tests the official package distribution by calling
# the test-all and update-latest-report YML files.
#
name: "Test release"

on:
  schedule:
    - cron:  '00 2 * * *'
  workflow_dispatch:


jobs:
  test-all-master:
    name: "Test packages"
    uses: ./.github/workflows/test-all.yml
    with:
      which-gap: master

  update-latest-master:
    name: "Upload report"
    needs: test-all-master
    if: always()
    uses: ./.github/workflows/update-latest-report.yml
    with:
      which-gap: master

  test-all-4-11-1:
      name: "Test packages"
      uses: ./.github/workflows/test-all.yml
      with:
        which-gap: 4.11.1

  update-latest-4-11:
    name: "Upload report"
    needs: test-all-4-11-1
    if: always()
    uses: ./.github/workflows/update-latest-report.yml
    with:
      which-gap: 4.11.1
